site_name: Fiware-Orion
site_url: https://telefonicaid.github.io/fiware-orion/doc
repo_url: https://github.com/telefonicaid/fiware-orion.git
site_description: Orion Context Broker
docs_dir: ./
site_dir: html
markdown_extensions: [toc,fenced_code]
use_directory_urls: false
theme: readthedocs
extra_css: ["http://fiware.org/fiware.css"]
pages:
  - Home: README.md
  - 'Getting Started': 'doc/manuals/quick_start_guide.md'
  - 'User Manual':
      - Introduction: 'doc/manuals/user/walkthrough_apiv1.md'
      - 'Adding entities and attributes': 'doc/manuals/user/append_and_delete.md'
      - 'Attribute Metadata': 'doc/manuals/user/metadata.md'
      - 'Empty Types': 'doc/manuals/user/empty_types.md'
      - 'Structured values for attributes': 'doc/manuals/user/structured_attribute_valued.md'
      - Filtering: 'doc/manuals/user/filtering.md'
      - Pagination: 'doc/manuals/user/pagination.md'
      - Geolocation: 'doc/manuals/user/geolocation.md'
      - 'Context Providers': 'doc/manuals/user/context_providers.md'
      - 'Updating Registrations and Subscriptions': 'doc/manuals/user/updating_regs_and_subs.md'
      - 'Multi tenancy': 'doc/manuals/user/multitenancy.md'
      - 'Entity service paths': 'doc/manuals/user/service_path.md'
      - 'Context Broker federation': 'doc/manuals/user/federation.md'
      - 'Duration (for registrations and subscriptions)': 'doc/manuals/user/duration.md'
      - 'Mixing standard and convenience operations': 'doc/manuals/user/std_conv_mix.md'
      - 'HTTP and NGSI response codes': 'doc/manuals/user/http_and_ngsi_sc.md'
      - 'Security considerations': 'doc/manuals/user/security.md'
      - 'Known limitations': 'doc/manuals/user/known_limitations.md'
      - 'Forbidden characters': 'doc/manuals/user/forbidden_characters.md'
  - 'Admin Guide':
      - 'Building from Sources': 'doc/manuals/admin/build_source.md'
      - 'Running Orion from command line': 'doc/manuals/admin/cli.md'
      - 'Database administration': 'doc/manuals/admin/database_admin.md'
      - 'Data model': 'doc/manuals/admin/database_model.md'
      - 'Logs': 'doc/manuals/admin/logs.md'
      - 'Watchdog': 'doc/manuals/admin/watchdog.md'
      - 'Diagnosis': 'doc/manuals/admin/diagnosis.md'
      - 'Rush relayer': 'doc/manuals/admin/rush.md'
      - 'Management REST interface': 'doc/manuals/admin/management_api.md'
      - 'Resources & I/O flows': 'doc/manuals/admin/resources.md'
      - 'Upgrading from previous to 0.14.1': 'doc/manuals/admin/upgrading_crossing_0-14-1.md'
      - 'Upgrading from previous to 0.19.0': 'doc/manuals/admin/upgrading_crossing_0-19-0.md'
      - 'Upgrading from previous to 0.21.0': 'doc/manuals/admin/upgrading_crossing_0-21-0.md'